quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.info-title=Shipping Aggregator Lab
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=API de cotacao de frete com agregacao paralela via virtual threads.
shipping.partners.fastbox.delay-ms=180
shipping.partners.econoship.delay-ms=260
shipping.partners.picknpack.delay-ms=140
